title: MINDMIX
description: หลายเรื่อง หลายมุมมอง ในพื้นที่เดียว
lang: th
url: "https://alindaaladin13-collab.github.io"
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
show_excerpts: true
